package euler;
/**
 * 
 * @author PorssA
 *
 * DESCRIPTION:
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms.
 * By starting with 1 and 2, the first 10 terms will be:
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose values do not exceed 
 * four million, find the sum of the even-valued terms.
 *
 */
public class Euler2 {

	public static void main(String[] args) {
		int previous = 1;
		int current = 2;
		int tempCurrent = 0;
		
		int sum = 0;
		
		do{
			if(current % 2 == 0){
				sum+=current;
			}
			
			tempCurrent = current;
			current += previous;
			previous = tempCurrent;
			
			System.out.println("prev: " + previous + " | curr: " + current + " | sum: " + sum);
		}while(current < 4000000);

		System.out.println("END");
	}

}
